# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=320)),
                ('create_date', models.DateTimeField(verbose_name='Date created')),
            ],
        ),
    ]
