# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_auto_20160227_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='area',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='realname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
